# Generated by Django 5.2.6 on 2025-10-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
